### ISSUE TITLE
InvalidBamHeaderError

### ISSUE THREAD

**Issue by lpipes** [broadinstitute/viral-pipelines#418]
Any ideas on how to fix this?

```
Traceback (most recent call last):
  File "/opt/viral-ngs/source/read_utils.py", line 1484, in <module>
    util.cmd.main_argparse(__commands__, __doc__)
  File "/opt/viral-ngs/source/util/cmd.py", line 216, in main_argparse
    ret = args.func_main(args)
  File "/opt/viral-ngs/source/util/cmd.py", line 106, in _main
    mainfunc(**args2)
  File "/opt/viral-ngs/source/read_utils.py", line 1237, in align_and_fix
    mm2.align_bam(inBam, refFastaCopy, bam_aligned, threads=threads, options=aligner_options.split())
  File "/opt/viral-ngs/source/tools/minimap2.py", line 57, in align_bam
    raise InvalidBamHeaderError("{} lacks read groups".format(inBam))
NameError: name 'InvalidBamHeaderError' is not defined
```

**Comment by lpipes** [comment]
@dpark01 Ahh ok I wasn't aware of that workflow but I used it and it worked! thanks
